<a href="https://colab.research.google.com/github/deepak8186863620/Machine_Learning_Lab/blob/main/PCAanLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
iris=load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

print(" the dataset",iris)

 the dataset {'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4

#**checking for the shape of X and y axis**

In [2]:
print(" original data shape ",X.shape)

 original data shape  (150, 4)


In [4]:
print(" original  data of the Y",y.shape)

 original  data of the Y (150,)


In [8]:
mean=np.mean(X,axis=0)
std=np.std(X,axis=0)

#**Checking the standised values**


In [10]:
X_standardized=(X-mean)/std

In [11]:
print(" checking the standarized shape value ",X_standardized.shape)

 checking the standarized shape value  (150, 4)


In [12]:
Covarince_matrix=np.cov(X_standardized,rowvar=False)

In [14]:
print("\nCovariance Matrix:")
print(Covarince_matrix)



Covariance Matrix:
[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]


#**4 Compute Eigenvalues and Eigenvectors**


In [20]:
eigenvalues, eigenvectors = np.linalg.eigh(Covarince_matrix)
print(eigenvalues)


[0.02085386 0.14774182 0.9201649  2.93808505]


In [21]:
print("\nEigenvectors:")
print(eigenvectors)


Eigenvectors:
[[ 0.26128628  0.71956635  0.37741762 -0.52106591]
 [-0.12350962 -0.24438178  0.92329566  0.26934744]
 [-0.80144925 -0.14212637  0.02449161 -0.5804131 ]
 [ 0.52359713 -0.63427274  0.06694199 -0.56485654]]


#**5 Sort Eigenvalues in Descending Order**

In [22]:
sorted_indices = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

print("\nSorted Eigenvalues:")
print(eigenvalues)


Sorted Eigenvalues:
[2.93808505 0.9201649  0.14774182 0.02085386]


#**6. Explained Variance**

In [23]:
explained_variance = eigenvalues / np.sum(eigenvalues)

In [25]:
print("\nExplaining the  Variance Ratio:")
for i, value in enumerate(explained_variance):
    print(f"PC{i+1}: {value:.4f} "
          f"({value * 100:.2f}%)")


Explaining the  Variance Ratio:
PC1: 0.7296 (72.96%)
PC2: 0.2285 (22.85%)
PC3: 0.0367 (3.67%)
PC4: 0.0052 (0.52%)


#**# 7. Select Principal Components**